<?php

namespace Adrotec\BreezeJs\Metadata;

use JMS\Serializer\Annotation as Serializer;

/**
 * @Serializer\ExclusionPolicy("none")	
 */
class StructuralType {

    /**
     * @Serializer\Exclude
     */
    public $parentClass;

    /**
     * @Serializer\Exclude
     */
    public $reflectionClass;
    public $shortName;
    public $namespace;
    public $baseTypeName;
    public $isAbstract;
    public $isComplexType;
    public $autoGeneratedKeyType = 'Identity';
    public $defaultResourceName;
    public $dataProperties = array();
    public $navigationProperties;

}
