<?php

namespace BreezeJs\Metadata;

use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Exclude;



use ODataProducer\Providers\Metadata\ResourceType;
use ODataProducer\Providers\Metadata\ResourceProperty;
use ODataProducer\Providers\Metadata\ResourceTypeKind;
use ODataProducer\Providers\Metadata\ResourcePropertyKind;

/**
 * @ExclusionPolicy("none")	
 */
class StructuralType {

        /**
         * @Exclude
         */
        public $parentClass;
        
        /**
	 * @SerializedName("shortName")
	 */
	public $shortName;

	/**
	 * @SerializedName("namespace")
	 */
	public $namespace;
        
	/**
	 * @SerializedName("baseTypeName")
	 */
	public $baseTypeName;
        
	/**
	 * @SerializedName("isAbstract")
	 */
	public $isAbstract;

	/**
	 * @SerializedName("isComplexType")
	 */
	public $isComplexType;

	/**
	 * @SerializedName("autoGeneratedKeyType")
	 */
	public $autoGeneratedKeyType = 'Identity';

	/**
	 * @SerializedName("defaultResourceName")
	 */
	public $defaultResourceName;

	/**
	 * @SerializedName("dataProperties")
	 */
	public $dataProperties = array();

	/**
	 * @SerializedName("navigationProperties")
	 */
	public $navigationProperties;

}